name: yxcfip

on:
  workflow_dispatch:
  schedule:
    # 表达式生成 https://crontab.guru/
    - cron: '*/30 * * * *'
  push:
    paths:
      - 'secrets.ip.txt'
      - 'secrets.cfip.txt'
      - '.github/workflows/**'
      - '**.py'

jobs:
  yxcfip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run task
        env:
          url: ${{secrets.url}}
          ACTIONS_DEPLOY_KEY: ${{secrets.KEY}}
        run: |
          python yxcfip.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
          force_with_lease: true
          directory: .
      - name: Force push changes
        run: |
          git pull origin main
          git push origin main --force
